//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RomBe.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChildActivitiesHistory
    {
        public int ChildId { get; set; }
        public int TaskTypeId { get; set; }
        public int TaskId { get; set; }
        public int TaskStatusId { get; set; }
        public System.DateTime InsertDate { get; set; }
    
        public virtual Child Child { get; set; }
    }
}
