//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RomBe.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChildRealTimeSymptomsActivity
    {
        public int ChildId { get; set; }
        public int RealTimeSymptomsId { get; set; }
        public int RealTimeLeadingQuestionId { get; set; }
        public System.DateTime InsertDate { get; set; }
    
        public virtual Child Child { get; set; }
        public virtual RealTimeLeadingQuestion RealTimeLeadingQuestion { get; set; }
        public virtual RealTimeSymptom RealTimeSymptom { get; set; }
    }
}
