//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RomBe.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrudUserType
    {
        public CrudUserType()
        {
            this.CrudUsers = new HashSet<CrudUser>();
        }
    
        public int CrudUserTypeId { get; set; }
        public string UserType { get; set; }
        public System.DateTime InsertDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual ICollection<CrudUser> CrudUsers { get; set; }
    }
}
