//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RomBe.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrudUser
    {
        public CrudUser()
        {
            this.CrudUsersLogins = new HashSet<CrudUsersLogin>();
        }
    
        public string Username { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public int UserId { get; set; }
        public int CrudUserTypeId { get; set; }
        public System.DateTime InsertDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public Nullable<int> WorkingHoursInMinutes { get; set; }
    
        public virtual CrudUserType CrudUserType { get; set; }
        public virtual ICollection<CrudUsersLogin> CrudUsersLogins { get; set; }
    }
}
