//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RomBe.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Duplicate
    {
        public int TaskId { get; set; }
        public int TaskType { get; set; }
        public string PaginationType { get; set; }
        public int RowId { get; set; }
        public System.DateTime InsertDate { get; set; }
    }
}
