//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RomBe.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlobalParameter
    {
        public int GlobalParameterId { get; set; }
        public string ParameterName { get; set; }
        public string ParameterValueString { get; set; }
        public Nullable<int> ParameterValueInt { get; set; }
    }
}
