//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RomBe.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public Language()
        {
            this.MonthlyCheckLists = new HashSet<MonthlyCheckList>();
            this.MonthlyCheckupLists = new HashSet<MonthlyCheckupList>();
            this.ProActiveInformationContents = new HashSet<ProActiveInformationContent>();
            this.RealTimeLeadingQuestionContents = new HashSet<RealTimeLeadingQuestionContent>();
            this.RealTimeSolutionContents = new HashSet<RealTimeSolutionContent>();
            this.RealTimeSymptomsCongratulations = new HashSet<RealTimeSymptomsCongratulation>();
            this.RealTimeSymptomsContents = new HashSet<RealTimeSymptomsContent>();
            this.SystemMessages = new HashSet<SystemMessage>();
            this.Users = new HashSet<User>();
        }
    
        public int LanguageId { get; set; }
        public string LanguageName { get; set; }
        public System.DateTime InsertDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual ICollection<MonthlyCheckList> MonthlyCheckLists { get; set; }
        public virtual ICollection<MonthlyCheckupList> MonthlyCheckupLists { get; set; }
        public virtual ICollection<ProActiveInformationContent> ProActiveInformationContents { get; set; }
        public virtual ICollection<RealTimeLeadingQuestionContent> RealTimeLeadingQuestionContents { get; set; }
        public virtual ICollection<RealTimeSolutionContent> RealTimeSolutionContents { get; set; }
        public virtual ICollection<RealTimeSymptomsCongratulation> RealTimeSymptomsCongratulations { get; set; }
        public virtual ICollection<RealTimeSymptomsContent> RealTimeSymptomsContents { get; set; }
        public virtual ICollection<SystemMessage> SystemMessages { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
