//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RomBe.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthsList
    {
        public MonthsList()
        {
            this.MonthlyCheckLists = new HashSet<MonthlyCheckList>();
            this.MonthlyCheckupLists = new HashSet<MonthlyCheckupList>();
        }
    
        public int MonthId { get; set; }
        public string Name { get; set; }
        public System.DateTime InsertDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public byte Number { get; set; }
    
        public virtual ICollection<MonthlyCheckList> MonthlyCheckLists { get; set; }
        public virtual ICollection<MonthlyCheckupList> MonthlyCheckupLists { get; set; }
    }
}
