//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RomBe.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationLog
    {
        public Nullable<System.DateTime> SentDate { get; set; }
        public int UserId { get; set; }
        public Nullable<bool> IsSucceeded { get; set; }
        public string ErrorMessage { get; set; }
        public int NotificationId { get; set; }
        public int NotificationLogId { get; set; }
        public bool IsRead { get; set; }
        public int ChildId { get; set; }
    
        public virtual Child Child { get; set; }
        public virtual Notification Notification { get; set; }
        public virtual User User { get; set; }
    }
}
