//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RomBe.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeriodType
    {
        public PeriodType()
        {
            this.ProActiveInformations = new HashSet<ProActiveInformation>();
            this.RealTimeLeadingQuestions = new HashSet<RealTimeLeadingQuestion>();
            this.TaskCategories = new HashSet<TaskCategory>();
        }
    
        public int PeriodTypeId { get; set; }
        public string PeriodTypeName { get; set; }
        public System.DateTime InsertDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual ICollection<ProActiveInformation> ProActiveInformations { get; set; }
        public virtual ICollection<RealTimeLeadingQuestion> RealTimeLeadingQuestions { get; set; }
        public virtual ICollection<TaskCategory> TaskCategories { get; set; }
    }
}
