//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RomBe.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProActiveInformation
    {
        public ProActiveInformation()
        {
            this.ProActiveInformationContents = new HashSet<ProActiveInformationContent>();
        }
    
        public int ProActiveInformationId { get; set; }
        public int TaskCategoryId { get; set; }
        public int PeriodMin { get; set; }
        public int PeriodMax { get; set; }
        public string CreatedBy { get; set; }
        public string Subject { get; set; }
        public System.DateTime InsertDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int PeriodTypeId { get; set; }
        public int ProActiveTypeId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> UniqueId { get; set; }
    
        public virtual PeriodType PeriodType { get; set; }
        public virtual ProActiveType ProActiveType { get; set; }
        public virtual TaskCategory TaskCategory { get; set; }
        public virtual ICollection<ProActiveInformationContent> ProActiveInformationContents { get; set; }
    }
}
