//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RomBe.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealTimeSolution
    {
        public RealTimeSolution()
        {
            this.ChildRealTimeSolutionActivities = new HashSet<ChildRealTimeSolutionActivity>();
            this.RealTimeSolutionContents = new HashSet<RealTimeSolutionContent>();
        }
    
        public int RealTimeSolutionId { get; set; }
        public int RealTimeLeadingQuestionId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime InsertDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual ICollection<ChildRealTimeSolutionActivity> ChildRealTimeSolutionActivities { get; set; }
        public virtual RealTimeLeadingQuestion RealTimeLeadingQuestion { get; set; }
        public virtual ICollection<RealTimeSolutionContent> RealTimeSolutionContents { get; set; }
    }
}
