//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RomBe.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealTimeLeadingQuestion
    {
        public RealTimeLeadingQuestion()
        {
            this.ChildRealTimeSolutionActivities = new HashSet<ChildRealTimeSolutionActivity>();
            this.ChildRealTimeSymptomsActivities = new HashSet<ChildRealTimeSymptomsActivity>();
            this.RealTimeLeadingQuestionContents = new HashSet<RealTimeLeadingQuestionContent>();
            this.RealTimeSolutions = new HashSet<RealTimeSolution>();
            this.RealTimeSymptoms = new HashSet<RealTimeSymptom>();
            this.RealTimeSymptomsCongratulations = new HashSet<RealTimeSymptomsCongratulation>();
        }
    
        public int RealTimeLeadingQuestionId { get; set; }
        public int TaskCategoryId { get; set; }
        public int PeriodMin { get; set; }
        public int PeriodMax { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime InsertDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int PeriodTypeId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> UniqueId { get; set; }
    
        public virtual ICollection<ChildRealTimeSolutionActivity> ChildRealTimeSolutionActivities { get; set; }
        public virtual ICollection<ChildRealTimeSymptomsActivity> ChildRealTimeSymptomsActivities { get; set; }
        public virtual PeriodType PeriodType { get; set; }
        public virtual TaskCategory TaskCategory { get; set; }
        public virtual ICollection<RealTimeLeadingQuestionContent> RealTimeLeadingQuestionContents { get; set; }
        public virtual ICollection<RealTimeSolution> RealTimeSolutions { get; set; }
        public virtual ICollection<RealTimeSymptom> RealTimeSymptoms { get; set; }
        public virtual ICollection<RealTimeSymptomsCongratulation> RealTimeSymptomsCongratulations { get; set; }
    }
}
