//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RomBe.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemMessage
    {
        public int SystemMessageId { get; set; }
        public string MessageCode { get; set; }
        public int SystemMessageTypeId { get; set; }
        public string MessageTitle { get; set; }
        public string MessageContent { get; set; }
        public string OKButtonText { get; set; }
        public string CancelButtonText { get; set; }
        public string Comments { get; set; }
        public int LanguageId { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual SystemMessagesType SystemMessagesType { get; set; }
    }
}
