//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RomBe.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskCategory
    {
        public TaskCategory()
        {
            this.MonthlyCheckLists = new HashSet<MonthlyCheckList>();
            this.MonthlyCheckupLists = new HashSet<MonthlyCheckupList>();
            this.ProActiveInformations = new HashSet<ProActiveInformation>();
            this.RealTimeLeadingQuestions = new HashSet<RealTimeLeadingQuestion>();
        }
    
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public int PeriodTypeId { get; set; }
        public System.DateTime InsertDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual ICollection<MonthlyCheckList> MonthlyCheckLists { get; set; }
        public virtual ICollection<MonthlyCheckupList> MonthlyCheckupLists { get; set; }
        public virtual PeriodType PeriodType { get; set; }
        public virtual ICollection<ProActiveInformation> ProActiveInformations { get; set; }
        public virtual ICollection<RealTimeLeadingQuestion> RealTimeLeadingQuestions { get; set; }
    }
}
