//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RomBe.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Children = new HashSet<Child>();
            this.EmailLogs = new HashSet<EmailLog>();
            this.FacebookProviders = new HashSet<FacebookProvider>();
            this.GoogleProviders = new HashSet<GoogleProvider>();
            this.NotificationLogs = new HashSet<NotificationLog>();
            this.PregnantDetails = new HashSet<PregnantDetail>();
            this.UserDevices = new HashSet<UserDevice>();
            this.UserEmailActivations = new HashSet<UserEmailActivation>();
        }
    
        public int UserId { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public System.DateTime InsertDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public Nullable<int> Age { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> LocalTime { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<bool> IsPregnant { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> StateId { get; set; }
        public string City { get; set; }
        public int LanguageId { get; set; }
        public bool SendNotifications { get; set; }
        public bool IsActive { get; set; }
        public byte RegistartionSource { get; set; }
        public Nullable<byte> CampaignSource { get; set; }
        public string IpAddress { get; set; }
    
        public virtual ICollection<Child> Children { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<EmailLog> EmailLogs { get; set; }
        public virtual ICollection<FacebookProvider> FacebookProviders { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual ICollection<GoogleProvider> GoogleProviders { get; set; }
        public virtual Language Language { get; set; }
        public virtual ICollection<NotificationLog> NotificationLogs { get; set; }
        public virtual ICollection<PregnantDetail> PregnantDetails { get; set; }
        public virtual State State { get; set; }
        public virtual ICollection<UserDevice> UserDevices { get; set; }
        public virtual ICollection<UserEmailActivation> UserEmailActivations { get; set; }
    }
}
